<Project>
  <PropertyGroup>
    <Version>2.0.8</Version>
    <Company>Dynalektric</Company>
    <Product>Tally BigQuery Agent</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
